;/*FB_PKG_DELIM*/

__d("FriendingCometDeactivatedUserDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5155378287858237"}),null);
__d("FriendingCometDeactivatedUserDialogQuery$Parameters",["FriendingCometDeactivatedUserDialogQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("FriendingCometDeactivatedUserDialogQuery_facebookRelayOperation"),metadata:{},name:"FriendingCometDeactivatedUserDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("FriendingCometDeactivatedUserDialog.entrypoint",["FriendingCometDeactivatedUserDialogQuery$Parameters","JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{queryReference:{parameters:b("FriendingCometDeactivatedUserDialogQuery$Parameters"),variables:{id:a.userID}}}}},root:c("JSResourceForInteraction")("FriendingCometDeactivatedUserDialog.react").__setRef("FriendingCometDeactivatedUserDialog.entrypoint")};g["default"]=a}),98);
__d("ProfileCometAppCollectionContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b={collectionID:null,sectionID:null};c=a.createContext(b);g["default"]=c}),98);
__d("ProfileCometAppCollectionItemHovercardWrapper_timelineAppCollectionItem.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"ProfileCometAppCollectionItemHovercardWrapper_timelineAppCollectionItem",selections:[{alias:null,args:null,concreteType:null,kind:"LinkedField",name:"node",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null},{kind:"InlineFragment",selections:[{alias:null,args:[{kind:"Literal",name:"site",value:"www"}],kind:"ScalarField",name:"url",storageKey:'url(site:"www")'}],type:"Entity",abstractKey:"__isEntity"}],storageKey:null}],type:"TimelineAppCollectionItem",abstractKey:null};e.exports=a}),null);
__d("ProfileCometAppCollectionItemHovercardWrapper.react",["ActorHovercard.react","CometRelay","ProfileCometAppCollectionItemHovercardWrapper_timelineAppCollectionItem.graphql","canRenderHovercardForGraphQLEntityType","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=i||d("react");function a(a){var e=d("react-compiler-runtime").c(7),f=a.children;a=a.timelineAppCollectionItem;a=d("CometRelay").useFragment(h!==void 0?h:h=b("ProfileCometAppCollectionItemHovercardWrapper_timelineAppCollectionItem.graphql"),a);if(e[0]!==a.node){var g;g=(g=a.node)!=null?g:{};e[0]=a.node;e[1]=g}else g=e[1];g=g;var i=g.id;g=g.url;if(i!=null&&g!=null&&g!==""&&c("canRenderHovercardForGraphQLEntityType")((g=a.node)==null?void 0:g.__typename)){e[2]!==f||e[3]!==i?(a=j.jsx(c("ActorHovercard.react"),{actorID:i,children:f}),e[2]=f,e[3]=i,e[4]=a):a=e[4];return a}e[5]!==f?(g=f(null),e[5]=f,e[6]=g):g=e[6];return g}g["default"]=a}),98);
__d("ProfileCometAppCollectionNullState.react",["FDSText.react","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react");function a(a){var b=d("react-compiler-runtime").c(6),e=a.banner;a=a.message;var f;b[0]===Symbol["for"]("react.memo_cache_sentinel")?(f={className:"xq1608w x1p5oq8j"},b[0]=f):f=b[0];b[1]!==a?(f=i.jsx("div",babelHelpers["extends"]({},f,{children:i.jsx(c("FDSText.react"),{align:"center",color:"tertiary",type:"headlineEmphasized2",children:a})})),b[1]=a,b[2]=f):f=b[2];b[3]!==e||b[4]!==f?(a=i.jsxs(i.Fragment,{children:[e,f]}),b[3]=e,b[4]=f,b[5]=a):a=b[5];return a}g["default"]=a}),98);
__d("ProfileCometAppSectionNonSelfFriendsActionRenderer_actionsRenderer.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"ProfileCometAppSectionNonSelfFriendsActionRenderer_actionsRenderer",selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}],type:"TimelineAppSectionFriendsNonSelfActionRenderer",abstractKey:null};e.exports=a}),null);
__d("ProfileCometAppSectionNonSelfFriendsActionRenderer.react",["CometRelay","CometRow.react","CometRowItem.react","ProfileCometAppSectionNonSelfFriendsActionRenderer_actionsRenderer.graphql","ProfileCometAppSectionSearchControl.react","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=i||d("react");function a(a){var e=d("react-compiler-runtime").c(1);a=a.actionsRenderer;d("CometRelay").useFragment(h!==void 0?h:h=b("ProfileCometAppSectionNonSelfFriendsActionRenderer_actionsRenderer.graphql"),a);e[0]===Symbol["for"]("react.memo_cache_sentinel")?(a=j.jsx(c("CometRow.react"),{paddingHorizontal:0,paddingTop:0,spacing:8,verticalAlign:"center",children:j.jsx(c("CometRowItem.react"),{children:j.jsx(c("ProfileCometAppSectionSearchControl.react"),{})})}),e[0]=a):a=e[0];return a}g["default"]=a}),98);
__d("ProfileCometAppSectionNonSelfFriendsActionRenderer_actionsRenderer$normalization.graphql",[],(function(a,b,c,d,e,f){"use strict";a={kind:"SplitOperation",metadata:{},name:"ProfileCometAppSectionNonSelfFriendsActionRenderer_actionsRenderer$normalization",selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}]};e.exports=a}),null);